<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AparaturSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'nama' => 'MATHEUS SUMARDI',
                'jabatan' => 'Carik',
                'role_id' => 5,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'S1',
                'jurusan' => 'Akuntansi',
                'instansi' => 'Universitas Sanata Dharma',
                'tahun' => 2000,
                'sk' => '26/Kep.Lurah/2020',
                'tgl_sk' => '2020-05-11',
            ],
            [
                'nama' => 'YULI ANTININGSIH',
                'jabatan' => 'Staff Pamong Kalurahan',
                'role_id' => 5,
                'jk' => 'PEREMPUAN',
                'pendidikan' => 'SMA/K',
                'jurusan' => 'Perkantoran',
                'instansi' => 'SMK Sanjaya',
                'tahun' => 1987,
                'sk' => '9 Tahun 2025',
                'tgl_sk' => '2025-01-02',
            ],
            [
                'nama' => 'SUHARMIYATI',
                'jabatan' => 'Staff Pamong Kalurahan',
                'role_id' => 5,
                'jk' => 'PEREMPUAN',
                'pendidikan' => 'SMA/K',
                'jurusan' => 'IPA',
                'instansi' => 'SMA Budya Wacana 1',
                'tahun' => 1991,
                'sk' => '4 Tahun 2025',
                'tgl_sk' => '2025-01-02',
            ],
            [
                'nama' => 'WIDIYAWATI',
                'jabatan' => 'Staff Pamong Kalurahan',
                'role_id' => 5,
                'jk' => 'PEREMPUAN',
                'pendidikan' => 'SMA/K',
                'jurusan' => 'Marketing',
                'instansi' => 'SMK N 1 Tempel',
                'tahun' => 2007,
                'sk' => '7 Tahun 2025',
                'tgl_sk' => '2025-01-02',
            ],
            [
                'nama' => 'IRMAWATI',
                'jabatan' => 'Staff Pamong Kalurahan',
                'role_id' => 5,
                'jk' => 'PEREMPUAN',
                'pendidikan' => 'S1',
                'jurusan' => 'Ekonomi Management',
                'instansi' => 'Universitas Islam Indonesia',
                'tahun' => 2009,
                'sk' => '3 Tahun 2025',
                'tgl_sk' => '2025-01-02',
            ],
            [
                'nama' => 'HENI AMBARWATI',
                'jabatan' => 'Staff Pamong Kalurahan',
                'role_id' => 5,
                'jk' => 'PEREMPUAN',
                'pendidikan' => 'D3',
                'jurusan' => 'Teknologi Hasil Pertanian',
                'instansi' => 'Universitas Sebelas Maret',
                'tahun' => 2013,
                'sk' => '6 Tahun 2025',
                'tgl_sk' => '2025-01-02',
            ],
            [
                'nama' => 'UMAR BUDIYANA',
                'jabatan' => 'Staff Pamong Kalurahan',
                'role_id' => 5,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'SMA/K',
                'jurusan' => 'Otomotif',
                'instansi' => 'SMK Muhammadiyah Pakem',
                'tahun' => 1991,
                'sk' => '5 Tahun 2025',
                'tgl_sk' => '2025-01-02',
            ],
            [
                'nama' => 'AGUS SUPRAPTO',
                'jabatan' => 'Kaur Pangripta',
                'role_id' => 5,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'D3',
                'jurusan' => 'Management Perusahaan',
                'instansi' => 'AMP YKPN',
                'tahun' => 1996,
                'sk' => '26/Kep.Lurah/2020',
                'tgl_sk' => '2020-05-11',
            ],
            [
                'nama' => 'ENDARJI DWI SUPRAPTO, S.IP',
                'jabatan' => 'Jagabaya',
                'role_id' => 5,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'S1',
                'jurusan' => 'Ilmu Pemerintahan',
                'instansi' => 'Universitas Gadjah Mada',
                'tahun' => 1993,
                'sk' => '26/Kep.Lurah/2020',
                'tgl_sk' => '2020-05-11',
            ],
            [
                'nama' => 'SRI HARTANTO',
                'jabatan' => 'Dukuh Jetisan',
                'role_id' => 3,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'D3',
                'jurusan' => 'Pendidikan Perwira Radio dan Operator Radio Elektronika',
                'instansi' => 'Operator Radio Umum',
                'tahun' => 1998,
                'sk' => '26/Kep.Lurah/2020',
                'tgl_sk' => '2020-05-11',
            ],
            [
                'nama' => 'MUHAMMAD EKO NUGROHO, SE',
                'jabatan' => 'Dukuh Purworejo',
                'role_id' => 3,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'S1',
                'jurusan' => 'Ekonomi Akuntansi',
                'instansi' => 'Universitas Islam Indonesia',
                'tahun' => 2006,
                'sk' => '26/Kep.Lurah/2020',
                'tgl_sk' => '2020-05-11',
            ],
            [
                'nama' => 'MARJUPRI',
                'jabatan' => 'Dukuh Boyong',
                'role_id' => 3,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'D3',
                'jurusan' => 'Ketatalaksanaan Pelayaran Niaga dan Kepelabuhan',
                'instansi' => 'Akademi Maritim Ganesha',
                'tahun' => 1998,
                'sk' => '26/Kep.Lurah/2020',
                'tgl_sk' => '2020-05-11',
            ],
            [
                'nama' => 'ANGGARA DANIAWAN',
                'jabatan' => 'Dukuh Kaliurang Timur',
                'role_id' => 3,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'S1',
                'jurusan' => 'Ilmu Ekonomi Studi Pembangunan',
                'instansi' => 'UPN Veteran Yogyakarta',
                'tahun' => 2005,
                'sk' => '26/Kep.Lurah/2020',
                'tgl_sk' => '2020-05-11',
            ],
            [
                'nama' => 'ASEP WIDODO',
                'jabatan' => 'Dukuh Pandanpuro',
                'role_id' => 3,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'SMA/K',
                'jurusan' => 'Mekanik Umum',
                'instansi' => 'SMK Muhammadiyah Pakem',
                'tahun' => 2000,
                'sk' => '26/Kep.Lurah/2020',
                'tgl_sk' => '2020-05-11',
            ],
            [
                'nama' => 'MONIKA ESTI WIDYANINGSIH',
                'jabatan' => 'Dukuh Wonorejo',
                'role_id' => 3,
                'jk' => 'PEREMPUAN',
                'pendidikan' => 'S1',
                'jurusan' => 'Pendidikan Akuntansi',
                'instansi' => 'Universitas Sanata Dharma',
                'tahun' => 2007,
                'sk' => '26/Kep.Lurah/2020',
                'tgl_sk' => '2020-05-11',
            ],
            [
                'nama' => 'MARSUDI',
                'jabatan' => 'Dukuh Randu',
                'role_id' => 3,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'SMA/K',
                'jurusan' => 'Pertanian',
                'instansi' => 'SPBMA',
                'tahun' => 1986,
                'sk' => '26/Kep.Lurah/2020',
                'tgl_sk' => '2020-05-11',
            ],
            [
                'nama' => 'YULIASTUTI',
                'jabatan' => 'Kaur Tata Laksana',
                'role_id' => 5,
                'jk' => 'PEREMPUAN',
                'pendidikan' => 'D3',
                'jurusan' => 'Pendidikan Umum',
                'instansi' => 'Universitas Sarjana Wiyata',
                'tahun' => 1985,
                'sk' => '26/Kep.Lurah/2020',
                'tgl_sk' => '2020-05-11',
            ],
            [
                'nama' => 'WAHYU ISHARYANTA, A.MD',
                'jabatan' => 'Dukuh Banteng',
                'role_id' => 3,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'D3',
                'jurusan' => 'Ketatalaksanaan Pelayaran Niaga dan Kepelabuhan',
                'instansi' => 'Akademi Maritim Ganesha',
                'tahun' => 1998,
                'sk' => '26/Kep.Lurah/2020',
                'tgl_sk' => '2020-05-11',
            ],
            [
                'nama' => 'FRANSISKUS XAVERIUS SUHADI WIYONO',
                'jabatan' => 'Ulu - Ulu',
                'role_id' => 5,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'SMA/K',
                'jurusan' => 'Perkantoran',
                'instansi' => 'SMK Sanjaya',
                'tahun' => 1981,
                'sk' => '26/Kep.Lurah/2020',
                'tgl_sk' => '2020-05-11',
            ],
            [
                'nama' => 'PUSPITA RAMA SARI',
                'jabatan' => 'Dukuh Ngipiksari',
                'role_id' => 3,
                'jk' => 'PEREMPUAN',
                'pendidikan' => 'S1',
                'jurusan' => 'PGSD FKIP',
                'instansi' => 'IKIP PGRI Yogyakarta',
                'tahun' => 2011,
                'sk' => '50 Tahun 2023',
                'tgl_sk' => '2023-07-13',
            ],
            [
                'nama' => 'SUHARDI',
                'jabatan' => 'Dukuh Tanen',
                'role_id' => 3,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'SMA/K',
                'jurusan' => 'IPA',
                'instansi' => 'Madrasah Aliyah Negeri Pakem',
                'tahun' => 2001,
                'sk' => 'Kep.Lur no 25.1 tahun 2021',
                'tgl_sk' => '2021-08-04',
            ],
            [
                'nama' => 'AMIN SARJITO',
                'jabatan' => 'Lurah',
                'role_id' => 5,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'S1',
                'jurusan' => 'Hukum',
                'instansi' => 'Universitas Widya Mataram',
                'tahun' => 2013,
                'sk' => '43.80/Kep.KDH/A/2024',
                'tgl_sk' => '2024-06-27',
            ],
            [
                'nama' => 'P. DIKA PRASETYO WIBISONO',
                'jabatan' => 'Dukuh Sawungan',
                'role_id' => 3,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'S1',
                'jurusan' => 'Sastra Indonesia',
                'instansi' => 'Universitas Sanata Darma',
                'tahun' => 2013,
                'sk' => '54 Tahun 2023',
                'tgl_sk' => '2023-09-15',
            ],
            [
                'nama' => 'MUJIYONO',
                'jabatan' => 'Kamituwa',
                'role_id' => 5,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'SMA/K',
                'jurusan' => 'IPA',
                'instansi' => 'SMA N 1 NGAGLIK',
                'tahun' => 1990,
                'sk' => '26/Kep.Lurah/2020',
                'tgl_sk' => '2020-05-11',
            ],
            [
                'nama' => 'SUKISNO',
                'jabatan' => 'Staff Pamong Kalurahan',
                'role_id' => 5,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'SMA/K',
                'jurusan' => 'Pertanian',
                'instansi' => 'SFMA Kanisius',
                'tahun' => 1993,
                'sk' => '8 Tahun 2025',
                'tgl_sk' => '2025-01-02',
            ],
            [
                'nama' => 'SEPTIAN WARIANTI',
                'jabatan' => 'Staff Pamong Kalurahan',
                'role_id' => 5,
                'jk' => 'PEREMPUAN',
                'pendidikan' => 'S1',
                'jurusan' => 'Sistem Informasi',
                'instansi' => 'Universitas Respati Yogyakarta',
                'tahun' => 2022,
                'sk' => '10 Tahun 2025',
                'tgl_sk' => '2025-01-02',
            ],
            [
                'nama' => 'SATRIYA PANDU PERMANA',
                'jabatan' => 'Dukuh Kaliurang Barat',
                'role_id' => 3,
                'jk' => 'LAKI-LAKI',
                'pendidikan' => 'SMA/K',
                'jurusan' => null,
                'instansi' => '-',
                'tahun' => 2024,
                'sk' => '33',
                'tgl_sk' => '2024-03-25',
            ],
        ];

        foreach ($data as $index => $item) {

            $userId = DB::table('users')->insertGetId([
                'role_id' => $item['role_id'],
                'dusun_id' => 1,
                'nik' => '340401' . str_pad($index + 1, 10, '0', STR_PAD_LEFT),
                'nama_lengkap' => $item['nama'],
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '1980-01-01',
                'jenis_kelamin' => $item['jk'],
                'pekerjaan' => $item['jabatan'],
                'pendidikan_terakhir' => $item['pendidikan'],
                'status_perkawinan' => 'Kawin',
                'agama' => 'Islam',
                'nomor_telepon' => '0812345678' . rand(10, 99),
                'email' => strtolower(str_replace([' ', ',', '.'], '', $item['nama'])) . '@gmail.com',
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            $aparaturId = DB::table('aparatur')->insertGetId([
                'user_id' => $userId,
                'nama_jabatan' => $item['jabatan'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            DB::table('riwayat_jabatan')->insert([
                'aparatur_id' => $aparaturId,
                'nama_jabatan' => $item['jabatan'],
                'nomor_sk' => $item['sk'],
                'tanggal_mulai' => $item['tgl_sk'],
                'tanggal_selesai' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            DB::table('riwayat_pendidikan')->insert([
                'aparatur_id' => $aparaturId,
                'tingkat_pendidikan' => $item['pendidikan'],
                'jurusan' => $item['jurusan'],
                'nama_instansi' => $item['instansi'],
                'tahun_masuk' => $item['tahun'] - 4,
                'tahun_selesai' => $item['tahun'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}